### ISSUE TITLE
Personal additions

### ISSUE THREAD

**Issue by SilasCundiff** [KennethLuczko/myroutebuddy#39]
Hey, @KennethLuczko. Love the app!

I wanted to add some things I thought would be helpful for planning my own routes and I got a bit carried away.

If you would like me to cherry pick any of these additions, I can pull them out and add them to individual branches for prs. I usually work as a solo dev, so my branch etiquette is lacking.

Here is a list of the additions:
- Add Step Number indicator
- Add Region icons
- Add Sticky Stats calculator
- Update Card layout to make room for buttons
- Add color picker for highlighting tasks
- Add "Quick Insert Custom" button. (This adds a new custom task to below the current task, so you don't have to drag it up from the bottom of the list.)
- Add Search bar to "Your Route" (I also added one to "Available Tasks" before I saw you added your own already 😅)

There are some various other CSS tweaks to account for the new buttons and icons.

The colors save to the JSON and should work with any existing exported routes. 

If a task has a color applied, it will have a single property added to the JSON.
E.G: `"color": "blue"`

The branch with the full commit history can be found [here](https://github.com/SilasCundiff/myroutebuddy/commits/card-improvements/).

![image](https://github.com/user-attachments/assets/6c922d06-2dee-4023-94a2-eea141a20859)

**Comment by KennethLuczko** [comment]
Hi @SilasCundiff this is fantastic! Let's add all of these to the main app. Can you open a pull request with all of these features? I'll review and merge asap.
